version: 2.1

jobs:
  go111:
    docker:
      - image: circleci/golang:1.11.13
    steps:
      - checkout
      - restore_cache:
          keys:
            - '{{ .Environment.CIRCLE_JOB }}-{{ checksum "go.sum" }}'
      - run: go mod download
      - save_cache:
          key: '{{ .Environment.CIRCLE_JOB }}-{{ checksum "go.sum" }}'
          paths:
            - "/go/pkg/mod"
      - run: go test ./...

  go112:
    docker:
      - image: circleci/golang:1.12.9
    steps:
      - checkout
      - restore_cache:
          keys:
            - '{{ .Environment.CIRCLE_JOB }}-{{ checksum "go.sum" }}'
      - run: go mod download
      - save_cache:
          key: '{{ .Environment.CIRCLE_JOB }}-{{ checksum "go.sum" }}'
          paths:
            - "/go/pkg/mod"
      - run: go test ./... -coverprofile=/tmp/coverprofile -covermode=atomic

workflows:
  version: 2
  default:
    jobs:
      - go112
      - go111
